version: '3.8'

services:
  web:
    environment:
      - APP_ENV=development
    volumes:
      - ..:/app:rw
      - static_files:/data/checklist
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
